### ISSUE TITLE
Compilation errors on ubuntu 20.04.1

### ISSUE THREAD

**Issue by akhepcat** [mrlnc/eia0#2]
## Issue Description ##
Unable to compile from git on  Ubuntu 20.04 due to multiple errors.

## Setup Details ##
$ lsb_release -a
LSB Version:    core-11.1.0ubuntu2-noarch:security-11.1.0ubuntu2-noarch
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.1 LTS
Release:        20.04
Codename:       focal

$ gcc --version
gcc version 9.3.0 (Ubuntu 9.3.0-10ubuntu2) 

## Expected Behavior ##
(complete compilation)

## Actual Behaviour ##
1)  error in argument numbers  between  
LTE-ciphercheck/srsue/test/upper/rrc_meas_test.cc   and
LTE-ciphercheck/srsue/hdr/stack/rrc/rrc.h

1 is resolved by adding one additional 'nullptr' argument to  the rrc::init   arglest prior to the vararg {}

2)   I'm not familiar enough with c++  do diagnose this error:
/usr/local/src/LTE-work/LTE-ciphercheck/srsue/test/upper/nas_test.cc: In function ‘int security_command_test()’:
/usr/local/src/LTE-work/LTE-ciphercheck/srsue/test/upper/nas_test.cc:216:13: error: cannot declare variable ‘rrc_dummy’ to be of abstract type ‘srslte::rrc_dummy
  216 |   rrc_dummy rrc_dummy;
      |             ^~~~~~~~~
/usr/local/src/LTE-work/LTE-ciphercheck/srsue/test/upper/nas_test.cc:94:7: note:   because the following virtual functions are pure within ‘srslte::rrc_dummy’:
   94 | class rrc_dummy : public rrc_interface_nas
      |       ^~~~~~~~~
In file included from /usr/local/src/LTE-work/LTE-ciphercheck/srsue/test/upper/nas_test.cc:25:
/usr/local/src/LTE-work/LTE-ciphercheck/lib/include/srslte/interfaces/ue_interfaces.h:210:23: note:     ‘virtual void srsue::rrc_interface_nas::leave_connected()
  210 |   virtual void        leave_connected()                                                 = 0;
      |                       ^~~~~~~~~~~~~~~
/usr/local/src/LTE-work/LTE-ciphercheck/srsue/test/upper/nas_test.cc: In function ‘int mme_attach_request_test()’:
/usr/local/src/LTE-work/LTE-ciphercheck/srsue/test/upper/nas_test.cc:281:14: error: cannot declare variable ‘rrc_dummy’ to be of abstract type ‘srslte::rrc_dummy
  281 |   rrc_dummy  rrc_dummy;
      |              ^~~~~~~~~
/usr/local/src/LTE-work/LTE-ciphercheck/srsue/test/upper/nas_test.cc: In function ‘int esm_info_request_test()’:
/usr/local/src/LTE-work/LTE-ciphercheck/srsue/test/upper/nas_test.cc:358:13: error: cannot declare variable ‘rrc_dummy’ to be of abstract type ‘srslte::rrc_dummy
  358 |   rrc_dummy rrc_dummy;
      |             ^~~~~~~~~
/usr/local/src/LTE-work/LTE-ciphercheck/srsue/test/upper/nas_test.cc: In function ‘int dedicated_eps_bearer_test()’:
/usr/local/src/LTE-work/LTE-ciphercheck/srsue/test/upper/nas_test.cc:412:13: error: cannot declare variable ‘rrc_dummy’ to be of abstract type ‘srslte::rrc_dummy
  412 |   rrc_dummy rrc_dummy;
      |             ^~~~~~~~~
make[2]: *** [srsue/test/upper/CMakeFiles/nas_test.dir/build.make:63: srsue/test/upper/CMakeFiles/nas_test.dir/nas_test.cc.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:7816: srsue/test/upper/CMakeFiles/nas_test.dir/all] Error 2

--
i don't know if there are any additional errors after this, that are dependent on this file compiling correctly, but I *think* this is the only standout, based on make's output.

## Steps to reproduce the problem ##
clone from git,  mkdir build && cd build; cmake ..;  make -j4

## Additional Information ##
full build log available upon request

**Comment by mrlnc** [comment]
Try to specify the build target:
```
make srsue
```

I'm breaking the other targets (srsenb, tests, …), thus you get those errors. Not really good practice, but I want to change as little as possible. I think I'll adjust the Makefile to avoid building broken targets.

**Comment by akhepcat** [comment]
The above errors occurs  when   doing  'make -j4  srsue'  as well.

(snippet to show where  nas_test.cc  is in the build order:

[ 92%] Built target srslte_asn1_rrc_meas_test
[ 92%] Building CXX object srsue/test/upper/CMakeFiles/nas_test.dir/nas_test.cc.o
[ 92%] Built target srslte_asn1_rrc_ul_dcch_test

**Comment by mrlnc** [comment]
I removed the `srsue/test/` directory from the build with that commit. Try that patch and make sure to run `cmake` again (or even remove the build directory, too).

**Comment by akhepcat** [comment]
clean; pull; build.

100% complete.    Perfect, thanks!
